//获取数据成功
export const GET_NEWS_LIST_SUCC = 'GET_NEWS_LIST_SUCC'
//数据刷新
export const CHANGE_NEWS_LIST_REFRESHING = 'CHANGE_NEWS_LIST_REFRESHING'
//数据加载
export const CHANGE_NEWS_LIST_LOADINGMORE = 'CHANGE_NEWS_LIST_LOADINGMORE'
